version: "2.2"
services:
  jobmanager:
    image: huangxiaofenglogin/flink1.17-jdk11-scala12-hudi:latest
    ports:
      - "8181:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: huangxiaofenglogin/flink1.17-jdk11-scala12-hudi:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2     
